# This is a basic workflow to help you get started with Actions
name: Retire Inactive Contributors

# Controls when the workflow will run
on:
  # Run on a schedule
  schedule:
    - cron: "5 * * * *" 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  retire-inactive-contributors:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: cucumber/action-retire-inactive-contributor@main
